package jetbrains.mps.vclang.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import com.jetbrains.jetpad.vclang.term.Abstract;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This interface is not involved in the actual method invocation
 */
@Deprecated
public interface AbstractExpression_BehaviorDescriptor {
  public boolean virtual_isSurroundedWithBraces_2724597730929429700(SNode thisNode);
  public boolean virtual_isRightMost_2384453979682054949(SNode thisNode, SNode child);
  public boolean virtual_isLeftMost_2384453979682054999(SNode thisNode, SNode child);
  public Abstract.Expression virtual_toSourceExpression_7330199235213689458(SNode thisNode);
}
