package jetbrains.mps.vclang.behavior;

/*Generated by MPS */

import com.jetbrains.jetpad.vclang.term.Abstract;
import org.jetbrains.mps.openapi.model.SNode;

public class AdapterFactory {
  private static Correspondence<Abstract.SourceNode, SNode> adapters = new Correspondence();


}
