package jetbrains.mps.vclang.behavior;

/*Generated by MPS */

import com.jetbrains.jetpad.vclang.term.Abstract;
import java.util.List;
import com.jetbrains.jetpad.vclang.term.expr.arg.Utils;

public abstract class ArgumentAdapter implements Abstract.Argument {
  public void prettyPrint(StringBuilder builder, List<String> names, byte prec) {
    Utils.prettyPrintArgument(this, builder, names, prec, 0);
  }
}
