package jetbrains.mps.vclang.behavior;

/*Generated by MPS */

import java.util.Map;
import java.util.HashMap;

public class Correspondence<X, Y> {
  private Map<X, Y> reverseMap = new HashMap<X, Y>();
  private Map<Y, X> directMap = new HashMap<Y, X>();

  public void put(X x, Y y) {
    removeX(x);
    removeY(y);
    reverseMap.put(x, y);
    directMap.put(y, x);
  }

  public X getX(Y y) {
    return directMap.get(y);
  }

  public Y getY(X x) {
    return reverseMap.get(x);
  }

  public void removeX(X x) {
    Y y = getY(x);
    reverseMap.remove(x);
    directMap.remove(y);
  }

  public void removeY(Y y) {
    X x = getX(y);
    reverseMap.remove(x);
    directMap.remove(y);
  }
}
