package jetbrains.mps.vclang.behavior;

/*Generated by MPS */

import com.jetbrains.jetpad.vclang.term.Abstract;
import com.jetbrains.jetpad.vclang.term.definition.Universe;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import com.jetbrains.jetpad.vclang.term.expr.arg.Utils;
import org.jetbrains.mps.openapi.model.SNode;

public abstract class DefinitionAdapter implements Abstract.Definition {
  public Universe getUniverse() {
    return null;
  }
  public Abstract.Definition.Precedence getPrecedence() {
    return ((SLinkOperations.getTarget(getThisNode(), MetaAdapterFactory.getContainmentLink(0x2db233bb72db49c3L, 0xadc47ae97f87f8dcL, 0xc23f551009be72aL, 0xc23f55100992d5bL, "precedence")) == null) ? DEFAULT_PRECEDENCE : Precedence__BehaviorDescriptor.toSourcePrecedence_id5NQyKEZHnxj.invoke(SLinkOperations.getTarget(getThisNode(), MetaAdapterFactory.getContainmentLink(0x2db233bb72db49c3L, 0xadc47ae97f87f8dcL, 0xc23f551009be72aL, 0xc23f55100992d5bL, "precedence"))));
  }
  public Utils.Name getName() {
    return AdapterUtils.getName(getThisNode());
  }
  protected abstract SNode getThisNode();
}
