package jetbrains.mps.vclang.behavior;

/*Generated by MPS */

import java.util.List;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.scope.Scope;
import com.jetbrains.jetpad.vclang.term.Abstract;
import jetbrains.mps.smodel.behaviour.DefaultValuesHolder;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class LambdaExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor implements HasArguments_BehaviorDescriptor {
  public List<SNode> virtual_getArguments_1801596256174391532(SNode __thisNode__, boolean onlyExplicit) {
    return null;
  }
  public Scope virtual_getScope_3734116213129936182(SNode __thisNode__, SNode kind, SNode child) {
    return null;
  }
  public Scope virtual_getScope_7722139651431880752(SNode __thisNode__, SNode kind, String role, int index) {
    return null;
  }
  public List<Abstract.Argument> virtual_getSourceArguments_6698694374041979929(SNode __thisNode__) {
    return null;
  }
  public boolean virtual_isRightMost_2384453979682054949(SNode __thisNode__, SNode child) {
    return DefaultValuesHolder.defaultValue(Boolean.TYPE);
  }
  public Abstract.Expression virtual_toSourceExpression_7330199235213689458(SNode __thisNode__) {
    return null;
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.vclang.structure.LambdaExpression";
  }

}
