package jetbrains.mps.vclang.behavior;

/*Generated by MPS */

import java.util.List;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.scope.Scope;
import com.jetbrains.jetpad.vclang.term.Abstract;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.behaviour.DefaultValuesHolder;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class LetClause_BehaviorDescriptor extends BaseVcConcept_BehaviorDescriptor implements IVariable_BehaviorDescriptor, HasType_BehaviorDescriptor, HasArguments_BehaviorDescriptor {
  public List<SNode> virtual_getArguments_1801596256174391532(SNode __thisNode__, boolean onlyExplicit) {
    return null;
  }
  public String virtual_getFqName_1213877404258(SNode __thisNode__) {
    return null;
  }
  public Scope virtual_getScope_3734116213129936182(SNode __thisNode__, SNode kind, SNode child) {
    return null;
  }
  public Scope virtual_getScope_7722139651431880752(SNode __thisNode__, SNode kind, String role, int index) {
    return null;
  }
  public List<Abstract.Argument> virtual_getSourceArguments_6698694374041979929(SNode __thisNode__) {
    return null;
  }
  public boolean virtual_isCorrectVarName_7364609393485206679(SConcept __thisConcept__, String name) {
    return DefaultValuesHolder.defaultValue(Boolean.TYPE);
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.vclang.structure.LetClause";
  }

}
