package jetbrains.mps.vclang.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.behaviour.DefaultValuesHolder;
import com.jetbrains.jetpad.vclang.term.Abstract;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class PatternId_BehaviorDescriptor extends AbstractPattern_BehaviorDescriptor implements IVariable_BehaviorDescriptor, IPattern_BehaviorDescriptor {
  public String virtual_getFqName_1213877404258(SNode __thisNode__) {
    return null;
  }
  public boolean virtual_isCorrectVarName_7364609393485206679(SConcept __thisConcept__, String name) {
    return DefaultValuesHolder.defaultValue(Boolean.TYPE);
  }
  public Abstract.Pattern virtual_toSourcePattern_1390052907877755474(SNode __thisNode__) {
    return null;
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.vclang.structure.PatternId";
  }

}
