package jetbrains.mps.vclang.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import com.jetbrains.jetpad.vclang.term.Abstract;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class StaticModifier_BehaviorDescriptor extends BaseVcConcept_BehaviorDescriptor implements IClassMember_BehaviorDescriptor {
  public SNode virtual_getDefinition_2384453979674359704(SNode __thisNode__) {
    return null;
  }
  public Abstract.Statement virtual_toSourceStatement_4039004818823535932(SNode __thisNode__) {
    return null;
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.vclang.structure.StaticModifier";
  }

}
