package jetbrains.mps.vclang.intentions;

/*Generated by MPS */

import com.jetbrains.jetpad.vclang.module.Namespace;
import com.jetbrains.jetpad.vclang.term.expr.arg.Utils;
import com.jetbrains.jetpad.vclang.term.Abstract;

public class RootNamespace {
  private static Namespace rootNamespace = new Namespace(new Utils.Name("\\root", Abstract.Definition.Fixity.PREFIX));
  public static Namespace getRootNamespace() {
    return rootNamespace;
  }
}
