package jetbrains.mps.vclang.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;

public class ConstraintsAspectDescriptor implements jetbrains.mps.smodel.runtime.ConstraintsAspectDescriptor {
  public ConstraintsAspectDescriptor() {
  }
  public ConstraintsDescriptor getDescriptor(SConceptId conceptId) {
    long id = conceptId.getIdValue();
    if (id == 0x62a6e9940367a651L) {
      return new VariableExpression_Constraints();
    }
    if (id == 0xc23f551009b1df8L) {
      return new IValidIdentifier_Constraints();
    }
    if (id == 0xc23f551009b1e0dL) {
      return new IValidFunctionalSymbol_Constraints();
    }
    if (id == 0x75cfba109e316d2cL) {
      return new BinOpExpression_Constraints();
    }
    if (id == 0x40feb6e2a72ce3afL) {
      return new DefExpression_Constraints();
    }
    if (id == 0x62a6e9940367a6c1L) {
      return new TelescopeArgument_Constraints();
    }
    if (id == 0x634b3353f5ace1e6L) {
      return new AbstractArgument_Constraints();
    }
    if (id == 0x5cf68b0abfab6115L) {
      return new ImplicitArgument_Constraints();
    }
    if (id == 0x7b3886e81fa1cdbeL) {
      return new StaticModifier_Constraints();
    }
    if (id == 0x75cfba109e2ee299L) {
      return new AbstractConstructor_Constraints();
    }
    if (id == 0x5b62464c93378462L) {
      return new OverrideModifier_Constraints();
    }
    if (id == 0x1119e4631f266669L) {
      return new ConstructorWithPatterns_Constraints();
    }
    if (id == 0x134a75c1410d5ad1L) {
      return new PatternId_Constraints();
    }
    if (id == 0x13b91a232b9e7fd0L) {
      return new AbstractPattern_Constraints();
    }
    if (id == 0x134a75c1410d5ad4L) {
      return new PatternConstructor_Constraints();
    }
    if (id == 0x634b3353f5aea13cL) {
      return new AbstractClause_Constraints();
    }
    if (id == 0x61f824a8086f83a9L) {
      return new PatternParenthesis_Constraints();
    }
    if (id == 0x6168f46017309911L) {
      return new StaticFieldAccessOperation_Constraints();
    }
    return new BaseConstraintsDescriptor(conceptId);
  }
}
