package jetbrains.mps.vclang.editor;

/*Generated by MPS */

import jetbrains.mps.openapi.editor.EditorComponent;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.nodeEditor.cells.CellConditions;
import jetbrains.mps.nodeEditor.cells.EditorCell_Label;

public class EditorUtil {
  public static void selectNode(EditorComponent editor, SNode node) {
    EditorCell cell = editor.findNodeCell(node);
    if (cell != null) {
      EditorCell lastLeaf = ((jetbrains.mps.nodeEditor.cells.EditorCell) cell).getLastLeaf(CellConditions.SELECTABLE);
      editor.changeSelection(lastLeaf);
      if (lastLeaf instanceof EditorCell_Label) {
        ((EditorCell_Label) lastLeaf).end();
      }
    }
  }
}
