package jetbrains.mps.vclang.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.IntentionAspectBase;
import jetbrains.mps.intentions.IntentionFactory;
import org.jetbrains.annotations.Nullable;
import java.util.Collection;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import java.util.Arrays;

public final class IntentionsDescriptor extends IntentionAspectBase {
  private final long[] myId2Index;
  private IntentionFactory[] myIntentions0;
  private IntentionFactory[] myIntentions1;

  public IntentionsDescriptor() {
    myId2Index = new long[2];
    myId2Index[0] = 0xfc408c778ec305aL;
    myId2Index[1] = 0x16d1097f9c1c95c8L;
  }

  @Override
  @Nullable
  public Collection<IntentionFactory> getIntentions(@NotNull SConceptId conceptId) {
    final int index = Arrays.binarySearch(myId2Index, conceptId.getIdValue());
    switch (index) {
      case 0:
        // Concept: ClassDefinition 
        if (myIntentions0 == null) {
          myIntentions0 = new IntentionFactory[1];
          myIntentions0[0] = new TypeCheck_Intention();
        }
        return Arrays.asList(myIntentions0);
      case 1:
        // Concept: BaseVcConcept 
        if (myIntentions1 == null) {
          myIntentions1 = new IntentionFactory[1];
          myIntentions1[0] = new ShowWellTyped_Intention();
        }
        return Arrays.asList(myIntentions1);
      default:
        return null;
    }
  }

  @NotNull
  @Override
  public Collection<IntentionFactory> getAllIntentions() {
    IntentionFactory[] rv = new IntentionFactory[2];
    rv[0] = new TypeCheck_Intention();
    rv[1] = new ShowWellTyped_Intention();
    return Arrays.asList(rv);
  }
}
