package jetbrains.mps.vclang.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum AssociativitySwitch {
  _0("infixr", 0),
  _1("infixl", 1),
  _2("infix", 2);

  private final String myName;
  public String getName() {
    return myName;
  }
  private final int myValue;
  AssociativitySwitch(String name, int value) {
    myName = name;
    myValue = value;
  }
  public int getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return Integer.toString(myValue);
  }
  public static List<AssociativitySwitch> getConstants() {
    List<AssociativitySwitch> list = ListSequence.fromList(new LinkedList<AssociativitySwitch>());
    ListSequence.fromList(list).addElement(AssociativitySwitch._0);
    ListSequence.fromList(list).addElement(AssociativitySwitch._1);
    ListSequence.fromList(list).addElement(AssociativitySwitch._2);
    return list;
  }
  public static AssociativitySwitch getDefault() {
    return AssociativitySwitch._0;
  }
  public static AssociativitySwitch parseValue(String value) {
    if (value == null) {
      return AssociativitySwitch.getDefault();
    }
    if (value.equals(AssociativitySwitch._0.getValueAsString())) {
      return AssociativitySwitch._0;
    }
    if (value.equals(AssociativitySwitch._1.getValueAsString())) {
      return AssociativitySwitch._1;
    }
    if (value.equals(AssociativitySwitch._2.getValueAsString())) {
      return AssociativitySwitch._2;
    }
    return AssociativitySwitch.getDefault();
  }
}
