package jetbrains.mps.vclang.behavior;

/*Generated by MPS */


public class AbstractScopeCommand_BehaviorDescriptor extends BaseVcConcept_BehaviorDescriptor implements IClassMember_BehaviorDescriptor {
  public AbstractScopeCommand_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.vclang.structure.AbstractScopeCommand";
  }
}
