package jetbrains.mps.vclang.behavior;

/*Generated by MPS */


public abstract class AbstractScopeRequestDescriptor {
  protected boolean myOrder = false;
  public boolean isChildrenFirst() {
    return myOrder;
  }
}
