package jetbrains.mps.vclang.behavior;

/*Generated by MPS */

import com.jetbrains.jetpad.vclang.term.Abstract;
import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public abstract class AbstractClause_BehaviorDescriptor extends BaseVcConcept_BehaviorDescriptor {

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.vclang.structure.AbstractClause";
  }

  public abstract Abstract.Clause virtual_toSourceClause_3871692118594316597(SNode __thisNode__);
}
