package jetbrains.mps.vclang.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import com.jetbrains.jetpad.vclang.term.Abstract;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;

public class AbstractArgument_Behavior {
  public static void init(SNode thisNode) {
  }
  public static Abstract.SourceNode virtual_toSourceNode_7330199235213647267(SNode thisNode) {
    return BehaviorReflection.invokeVirtual(Abstract.Argument.class, thisNode, "virtual_toSourceArgument_7330199235213968318", new Object[]{});
  }
}
