package jetbrains.mps.vclang.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SEnumOperations;

public class AbstractBinOpExpression_Behavior {
  public static void init(SNode thisNode) {
  }
  public static int virtual_getPriority_7707026478727611842(SNode thisNode) {
    return 10;
  }
  public static int virtual_getAssociativity_7707026478727627484(SNode thisNode) {
    return Integer.parseInt(SEnumOperations.getEnumMemberValue(SEnumOperations.getEnumMember(SEnumOperations.getEnum("r:246c3929-daa2-4b6b-b4cd-401ea917e5f6(jetbrains.mps.vclang.structure)", "AssociativitySwitch"), "2")));
  }
}
