package jetbrains.mps.vclang.behavior;

/*Generated by MPS */

import com.jetbrains.jetpad.vclang.term.Abstract;
import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public abstract class AbstractConstructor_BehaviorDescriptor extends Definition_BehaviorDescriptor implements IDataTypeConstructor_BehaviorDescriptor {

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.vclang.structure.AbstractConstructor";
  }

  public abstract Abstract.Constructor virtual_toSourceConstructor_6698694374042393223(SNode __thisNode__);
}
