package jetbrains.mps.vclang.behavior;

/*Generated by MPS */

import com.jetbrains.jetpad.vclang.term.Abstract;

public class AdapterUtils {
  public static Abstract.Definition.Arrow convertArrow(int arrow) {
    if (arrow == 0) {
      return Abstract.Definition.Arrow.LEFT;
    } else {
      return Abstract.Definition.Arrow.RIGHT;
    }
  }

  public static Abstract.Definition.Associativity convertAssoc(int assoc) {
    switch (assoc) {
      case 0:
        return Abstract.Definition.Associativity.RIGHT_ASSOC;
      case 1:
        return Abstract.Definition.Associativity.LEFT_ASSOC;
      default:
        return Abstract.Definition.Associativity.NON_ASSOC;
    }
  }
}
