package jetbrains.mps.vclang.behavior;

/*Generated by MPS */

import com.jetbrains.jetpad.vclang.term.Abstract;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SEnumOperations;
import com.jetbrains.jetpad.vclang.term.expr.arg.Utils;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.vclang.intentions.TypeCheckUtils;
import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;
import jetbrains.mps.internal.collections.runtime.ISelector;

public class AdapterUtils {
  private static Correspondence<Abstract.SourceNode, SNode> source = new Correspondence();
  private static Correspondence<Abstract.SourceNode, SNode> wellTyped = new Correspondence();

  public static Abstract.Definition.Arrow convertArrow(int arrow) {
    if (arrow == 0) {
      return Abstract.Definition.Arrow.LEFT;
    } else if (arrow == 1) {
      return Abstract.Definition.Arrow.RIGHT;
    } else {
      return null;
    }
  }

  public static SNode convertArrow2(Abstract.Definition.Arrow arrow) {
    if (arrow == Abstract.Definition.Arrow.LEFT) {
      return SEnumOperations.getEnumMember(SEnumOperations.getEnum("r:246c3929-daa2-4b6b-b4cd-401ea917e5f6(jetbrains.mps.vclang.structure)", "ArrowSwitch"), "0");
    }
    if (arrow == Abstract.Definition.Arrow.RIGHT) {
      return SEnumOperations.getEnumMember(SEnumOperations.getEnum("r:246c3929-daa2-4b6b-b4cd-401ea917e5f6(jetbrains.mps.vclang.structure)", "ArrowSwitch"), "1");
    }
    return SEnumOperations.getEnumMember(SEnumOperations.getEnum("r:246c3929-daa2-4b6b-b4cd-401ea917e5f6(jetbrains.mps.vclang.structure)", "ArrowSwitch"), "2");
  }

  public static Abstract.Definition.Associativity convertAssoc(int assoc) {
    switch (assoc) {
      case 0:
        return Abstract.Definition.Associativity.RIGHT_ASSOC;
      case 1:
        return Abstract.Definition.Associativity.LEFT_ASSOC;
      default:
        return Abstract.Definition.Associativity.NON_ASSOC;
    }
  }

  public static void rememberAdapter(SNode d, Abstract.SourceNode adapter) {
    source.put(adapter, d);
  }

  public static SNode resolveNode(Abstract.SourceNode def) {
    return source.getY(def);
  }

  public static Abstract.SourceNode resolveDef(SNode node) {
    return source.getX(node);
  }

  public static Utils.Name getName(SNode def) {
    return new Utils.Name(SPropertyOperations.getString(def, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")), ((boolean) Definition__BehaviorDescriptor.isInfix_id6oOmj_oc_dk.invoke(def) ? Abstract.Definition.Fixity.INFIX : Abstract.Definition.Fixity.PREFIX));
  }

  public static void setWellTyped(SNode source, Abstract.SourceNode wellTypedExpr) {
    source.putUserObject(TypeCheckUtils.KEY, wellTypedExpr);
    wellTyped.put(wellTypedExpr, source);
  }

  public static Object getWellTyped(SNode node) {
    return node.getUserObject(TypeCheckUtils.KEY);
  }

  public static SNode getRaw(Abstract.SourceNode wellTypedExpr) {
    return wellTyped.getY(wellTypedExpr);
  }

  public static List<String> getPath(SNode b) {
    List<String> result = ListSequence.fromList(ListSequence.fromList(SNodeOperations.getNodeAncestors(b, null, true)).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SNodeOperations.isInstanceOf(it, MetaAdapterFactory.getInterfaceConcept(0x2db233bb72db49c3L, 0xadc47ae97f87f8dcL, 0x380d6d7bb00e7ce0L, "jetbrains.mps.vclang.structure.VcLangNamespace"));
      }
    }).select(new ISelector<SNode, String>() {
      public String select(SNode it) {
        return (String) VcLangNamespace__BehaviorDescriptor.getNamespaceName_id3wdrnIK3K7o.invoke(SNodeOperations.cast(it, MetaAdapterFactory.getInterfaceConcept(0x2db233bb72db49c3L, 0xadc47ae97f87f8dcL, 0x380d6d7bb00e7ce0L, "jetbrains.mps.vclang.structure.VcLangNamespace")));
      }
    }).toListSequence()).reversedList();
    if (SNodeOperations.isInstanceOf(b, MetaAdapterFactory.getInterfaceConcept(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, "jetbrains.mps.lang.core.structure.INamedConcept")) && !(ListSequence.fromList(result).last().equals(SPropertyOperations.getString(SNodeOperations.cast(b, MetaAdapterFactory.getInterfaceConcept(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, "jetbrains.mps.lang.core.structure.INamedConcept")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"))))) {
      ListSequence.fromList(result).addElement(SPropertyOperations.getString(SNodeOperations.cast(b, MetaAdapterFactory.getInterfaceConcept(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, "jetbrains.mps.lang.core.structure.INamedConcept")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")));
    }
    return result;
  }


}
