package jetbrains.mps.vclang.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public class ArrowExpression_Behavior {
  public static void init(SNode thisNode) {
  }
  public static int virtual_getPriority_7707026478727611842(SNode thisNode) {
    return -4;
  }
}
