package jetbrains.mps.vclang.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import com.jetbrains.jetpad.vclang.term.Abstract;

public class BaseVcConcept_Behavior {
  public static void init(SNode thisNode) {
  }
  public static Abstract.SourceNode virtual_toSourceNode_7330199235213647267(SNode thisNode) {
    return null;
  }
}
