package jetbrains.mps.vclang.behavior;

/*Generated by MPS */

import com.jetbrains.jetpad.vclang.term.Abstract;
import org.jetbrains.mps.openapi.model.SNode;
import com.jetbrains.jetpad.vclang.term.definition.Definition;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.List;
import com.jetbrains.jetpad.vclang.term.expr.visitor.AbstractExpressionVisitor;

public class BinOpExpressionAdapter_ extends ExpressionAdapter implements Abstract.BinOpExpression {
  private SNode thisNode;
  public BinOpExpressionAdapter_(SNode t) {
    thisNode = t;
  }
  public Definition getBinOp() {
    // TODO: Implement getter 
    return null;
  }
  public Abstract.ArgumentExpression getLeft() {
    return new Abstract.ArgumentExpression() {
      public Abstract.Expression getExpression() {
        return BehaviorReflection.invokeVirtual(Abstract.Expression.class, SLinkOperations.getTarget(thisNode, MetaAdapterFactory.getContainmentLink(0x2db233bb72db49c3L, 0xadc47ae97f87f8dcL, 0x62a6e9940367a261L, 0x75cfba109e316b68L, "leftArg")), "virtual_toSourceExpression_7330199235213689458", new Object[]{});
      }
      public void prettyPrint(StringBuilder builder, List<String> names, byte prec) {
        getExpression().prettyPrint(builder, names, prec);
      }
      public boolean isExplicit() {
        return true;
      }
      public boolean isHidden() {
        return false;
      }
    };
  }
  public Abstract.ArgumentExpression getRight() {
    return new Abstract.ArgumentExpression() {
      public Abstract.Expression getExpression() {
        return BehaviorReflection.invokeVirtual(Abstract.Expression.class, SLinkOperations.getTarget(thisNode, MetaAdapterFactory.getContainmentLink(0x2db233bb72db49c3L, 0xadc47ae97f87f8dcL, 0x62a6e9940367a261L, 0x75cfba109e316b6aL, "rightArg")), "virtual_toSourceExpression_7330199235213689458", new Object[]{});
      }
      public void prettyPrint(StringBuilder builder, List<String> names, byte prec) {
        getExpression().prettyPrint(builder, names, prec);
      }
      public boolean isExplicit() {
        return true;
      }
      public boolean isHidden() {
        return false;
      }
    };
  }
  public <P, R> R accept(AbstractExpressionVisitor<? super P, ? extends R> visitor, P params) {
    return visitor.visitBinOp(this, params);
  }
}
