package jetbrains.mps.vclang.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import com.jetbrains.jetpad.vclang.term.Abstract;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class BracketExpression_Behavior {
  public static void init(SNode thisNode) {
  }
  public static Abstract.Expression virtual_toSourceExpression_7330199235213689458(SNode thisNode) {
    return BehaviorReflection.invokeVirtual(Abstract.Expression.class, SLinkOperations.getTarget(thisNode, MetaAdapterFactory.getContainmentLink(0x2db233bb72db49c3L, 0xadc47ae97f87f8dcL, 0x75cfba109e31841fL, 0x75cfba109e31843eL, "expression")), "virtual_toSourceExpression_7330199235213689458", new Object[]{});
  }
}
