package jetbrains.mps.vclang.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import com.jetbrains.jetpad.vclang.term.Abstract;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;

public class Constructor_Behavior {
  public static void init(SNode thisNode) {
  }
  public static Abstract.Definition virtual_toSourceDefinition_6698694374042209625(SNode thisNode) {
    return BehaviorReflection.invokeVirtual(Abstract.Constructor.class, thisNode, "virtual_toSourceConstructor_6698694374042393223", new Object[]{});
  }
  public static Abstract.Constructor virtual_toSourceConstructor_6698694374042393223(SNode thisNode) {
    return new ConstructorAdapter(thisNode);
  }
}
