package jetbrains.mps.vclang.behavior;

/*Generated by MPS */

import com.jetbrains.jetpad.vclang.term.Abstract;
import org.jetbrains.mps.openapi.model.SNode;
import com.jetbrains.jetpad.vclang.term.definition.Definition;
import com.jetbrains.jetpad.vclang.term.expr.visitor.AbstractExpressionVisitor;

public class DefCallExpressionAdapter_ extends ExpressionAdapter implements Abstract.DefCallExpression {
  private SNode thisNode;
  public DefCallExpressionAdapter_(SNode t) {
    thisNode = t;
  }
  public Definition getDefinition() {
    // TODO: Implement this 
    return null;
  }
  public <P, R> R accept(AbstractExpressionVisitor<? super P, ? extends R> visitor, P params) {
    return visitor.visitDefCall(this, params);
  }
}
