package jetbrains.mps.vclang.behavior;

/*Generated by MPS */

import com.jetbrains.jetpad.vclang.term.expr.arg.Utils;
import org.jetbrains.mps.openapi.model.SNode;
import com.jetbrains.jetpad.vclang.term.Abstract;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class DefExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor implements RefExpression_BehaviorDescriptor {
  public Utils.Name virtual_getInternalName_6660882825431946728(SNode __thisNode__) {
    return null;
  }
  public Abstract.Expression virtual_toSourceExpression_7330199235213689458(SNode __thisNode__) {
    return null;
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.vclang.structure.DefExpression";
  }

}
