package jetbrains.mps.vclang.behavior;

/*Generated by MPS */


public class DefExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public DefExpression_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.vclang.structure.DefExpression";
  }
}
