package jetbrains.mps.vclang.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.behaviour.DefaultValuesHolder;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public abstract class Expression_BehaviorDescriptor extends BaseVcConcept_BehaviorDescriptor implements AbstractExpression_BehaviorDescriptor {
  public boolean virtual_isLeftMost_2384453979682054999(SNode __thisNode__, SNode child) {
    return DefaultValuesHolder.defaultValue(Boolean.TYPE);
  }
  public boolean virtual_isRightMost_2384453979682054949(SNode __thisNode__, SNode child) {
    return DefaultValuesHolder.defaultValue(Boolean.TYPE);
  }
  public boolean virtual_isSurroundedWithBraces_2724597730929429700(SNode __thisNode__) {
    return DefaultValuesHolder.defaultValue(Boolean.TYPE);
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.vclang.structure.Expression";
  }

}
