package jetbrains.mps.vclang.behavior;

/*Generated by MPS */


public class Expression_BehaviorDescriptor extends BaseVcConcept_BehaviorDescriptor implements AbstractExpression_BehaviorDescriptor {
  public Expression_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.vclang.structure.Expression";
  }
}
