package jetbrains.mps.vclang.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Expression_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements AbstractExpression_BehaviorDescriptor {
  public Expression_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.vclang.structure.Expression";
  }
}
