package jetbrains.mps.vclang.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.ScopeProvider_BehaviorDescriptor;
import java.util.List;
import org.jetbrains.mps.openapi.model.SNode;
import com.jetbrains.jetpad.vclang.term.Abstract;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This interface is not involved in the actual method invocation
 */
@Deprecated
public interface HasArguments_BehaviorDescriptor extends IVcConcept_BehaviorDescriptor, ScopeProvider_BehaviorDescriptor {
  public List<SNode> virtual_getArguments_1801596256174391532(SNode thisNode, boolean onlyExplicit);
  public List<Abstract.Argument> virtual_getSourceArguments_6698694374041979929(SNode thisNode);
}
