package jetbrains.mps.vclang.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.ScopeProvider_BehaviorDescriptor;
import java.util.List;
import org.jetbrains.mps.openapi.model.SNode;

public interface HasArguments_BehaviorDescriptor extends IVcConcept_BehaviorDescriptor, ScopeProvider_BehaviorDescriptor {
  public List<SNode> virtual_getArguments_1801596256174391532(SNode thisNode, boolean onlyExplicit);
}
