package jetbrains.mps.vclang.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;

public interface IValidFunctionalSymbol_BehaviorDescriptor extends INamedConcept_BehaviorDescriptor {
  public boolean virtual_isCorrectFunctionalSymbol_7364609393485262972(SConcept thisConcept, String name);
}
