package jetbrains.mps.vclang.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;

public interface IValidFunctionalSymbol_BehaviorDescriptor extends INamedConcept_BehaviorDescriptor {
}
