package jetbrains.mps.vclang.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.regex.Pattern;

public class IValidIdentifier_Behavior {
  public static void init(SNode thisNode) {
  }
  public static boolean virtual_isCorrectVarName_7364609393485206679(SAbstractConcept thisConcept, String name) {
    return REGEXP_hye6x6_a0a0a1.matcher(name).matches();
  }
  private static Pattern REGEXP_hye6x6_a0a0a1 = Pattern.compile("[\\p{Alpha}_][\\p{Alnum}_\\-\\']*?", 0);
}
