package jetbrains.mps.vclang.behavior;

/*Generated by MPS */


public class OpenScopeCommand_BehaviorDescriptor extends AbstractScopeCommand_BehaviorDescriptor {
  public OpenScopeCommand_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.vclang.structure.OpenScopeCommand";
  }
}
