package jetbrains.mps.vclang.behavior;

/*Generated by MPS */


public class ProjExpression1_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public ProjExpression1_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.vclang.structure.ProjExpression1";
  }
}
