package jetbrains.mps.vclang.behavior;

/*Generated by MPS */

import com.jetbrains.jetpad.vclang.term.expr.arg.Utils;
import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This interface is not involved in the actual method invocation
 */
@Deprecated
public interface RefExpression_BehaviorDescriptor extends AbstractExpression_BehaviorDescriptor {
  public Utils.Name virtual_getInternalName_6660882825431946728(SNode thisNode);
}
