package jetbrains.mps.vclang.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import com.jetbrains.jetpad.vclang.term.Abstract;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;

public class TelescopeArgument_Behavior {
  public static void init(SNode thisNode) {
  }
  public static Abstract.Argument virtual_toSourceArgument_7330199235213968318(SNode thisNode) {
    return BehaviorReflection.invokeVirtual(Abstract.TypeArgument.class, thisNode, "virtual_toSourceTypedArgument_6698694374042025010", new Object[]{});
  }
  public static Abstract.TypeArgument virtual_toSourceTypedArgument_6698694374042025010(SNode thisNode) {
    return new TelescopeArgumentAdapter(thisNode);
  }
}
