package jetbrains.mps.vclang.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import java.util.List;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.internal.collections.runtime.ListSequence;

public class Variable_Behavior {
  public static void init(SNode thisNode) {
  }
  public static void virtual_addVariable_1644105782651964639(SNode thisNode, AbstractScopeRequestDescriptor descriptor, List<SNode> result) {
    if ((!(SPropertyOperations.getString(thisNode, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).equals("_"))) && descriptor instanceof ReferentVariableRequestDescriptor) {
      ListSequence.fromList(result).addElement(thisNode);
    }
  }
}
