package jetbrains.mps.vclang.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import com.jetbrains.jetpad.vclang.term.Abstract;

public class Variable_Behavior {
  public static void init(SNode thisNode) {
  }
  public static Abstract.Argument virtual_toSourceArgument_7330199235213968318(SNode thisNode) {
    return new VariableAdapter(thisNode);
  }
}
