package jetbrains.mps.vclang.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This interface is not involved in the actual method invocation
 */
@Deprecated
public interface VcLangNamespace_BehaviorDescriptor extends INamedConcept_BehaviorDescriptor {
  public String virtual_getNamespaceName_4039004818823381464(SNode thisNode);
}
