package jetbrains.mps.vclang.editor;

/*Generated by MPS */

import jetbrains.mps.openapi.editor.cells.EditorCell;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.openapi.editor.cells.CellActionType;
import jetbrains.mps.editor.runtime.cells.AbstractCellAction;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class BinOpLeftArgument_Action {
  public static void setCellActions(EditorCell editorCell, SNode node, EditorContext context) {
    editorCell.setAction(CellActionType.DELETE, new BinOpLeftArgument_Action.BinOpLeftArgument_Action_DELETE(node));
    editorCell.setAction(CellActionType.BACKSPACE, new BinOpLeftArgument_Action.BinOpLeftArgument_Action_BACKSPACE(node));
  }
  public static class BinOpLeftArgument_Action_DELETE extends AbstractCellAction {
    /*package*/ SNode myNode;
    public BinOpLeftArgument_Action_DELETE(SNode node) {
      this.myNode = node;
    }
    public void execute(EditorContext editorContext) {
      this.execute_internal(editorContext, this.myNode);
    }
    public void execute_internal(EditorContext editorContext, SNode node) {
      SNode rightExpression = SLinkOperations.getTarget(node, MetaAdapterFactory.getContainmentLink(0x2db233bb72db49c3L, 0xadc47ae97f87f8dcL, 0x62a6e9940367a261L, 0x75cfba109e316b6aL, "rightArg"));
      SNodeOperations.replaceWithAnother(node, rightExpression);
      editorContext.flushEvents();
      EditorUtil.selectNode(editorContext.getEditorComponent(), rightExpression);
    }
  }
  public static class BinOpLeftArgument_Action_BACKSPACE extends AbstractCellAction {
    /*package*/ SNode myNode;
    public BinOpLeftArgument_Action_BACKSPACE(SNode node) {
      this.myNode = node;
    }
    public void execute(EditorContext editorContext) {
      this.execute_internal(editorContext, this.myNode);
    }
    public void execute_internal(EditorContext editorContext, SNode node) {
      SNode rightExpression = SLinkOperations.getTarget(node, MetaAdapterFactory.getContainmentLink(0x2db233bb72db49c3L, 0xadc47ae97f87f8dcL, 0x62a6e9940367a261L, 0x75cfba109e316b6aL, "rightArg"));
      SNodeOperations.replaceWithAnother(node, rightExpression);
      editorContext.flushEvents();
      EditorUtil.selectNode(editorContext.getEditorComponent(), rightExpression);
    }
  }
}
