package jetbrains.mps.vclang.actions;

/*Generated by MPS */

import jetbrains.mps.scope.FilteringScope;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.scope.Scope;
import org.jetbrains.mps.openapi.model.SNode;

public class BinaryScope extends FilteringScope {

  public BinaryScope(@NotNull Scope scope) {
    super(scope);
  }
  @Override
  public boolean isExcluded(SNode node) {
    return false;
  }
}
